# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: 'restore .net'
  inputs:
    command: 'restore'
    projects: '**/*.sln'
    feedsToUse: 'select'
    configuration: 'release'
- task: DotNetCoreCLI@2
  displayName: 'build .net'
  inputs:
    command: 'build'
    projects: '**/*.sln'
    configuration: 'release'
- task: DotNetCoreCLI@2
  displayName: 'test .net'
  inputs:
    command: 'test'
    projects: '**/*.sln'
    configuration: 'release'
