# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.0'

- task: DotNetCoreCLI@2
  displayName: 'restore .net'
  inputs:
    command: 'restore'
    projects: '/Geetanjali.Yadav/e.shop'
    feedsToUse: 'select'
    configuration: 'release'
- task: DotNetCoreCLI@2
  displayName: 'build .net'
  inputs:
    command: 'build'
    projects: '/Geetanjali.Yadav/e.shop'
    configuration: 'release'
- task: DotNetCoreCLI@2
  displayName: 'test .net'
  inputs:
    command: 'test'
    projects: /Geetanjali.Yadav/e.shop'
    configuration: 'release'
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    zipAfterPublish: false
    workingDirectory: '/Geetanjali.Yadav/e.shop'
